name: 'dbt_project'
version: '1.0.0'
profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:

    bronze:
      +materialized: view

    silver:
      +materialized: view

    gold:
      +materialized: table

seeds:
  dbt_project:

    raw_customers:
      +column_types:
        customer_id: integer
        name: varchar
        email: varchar
        created_at: timestamp

    raw_products:
      +column_types:
        product_id: integer
        product_name: varchar
        category: varchar
        price: integer
        created_at: timestamp

    raw_orders:
      +column_types:
        order_id: integer
        customer_id: integer
        product_id: integer
        order_date: timestamp
        amount: integer